[package]
name = "balancer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.4"
log = "0.4"
actix-web = "4.0.0-beta.3"
actix-rt = "2.0.2"
dotenv = "0.15.0"
